### PR TITLE
First branch pull request

### PR DESCRIPTION
**Pull request by KoltonMain7**

### CODE REVIEW

**Comment by heyshadowsmith** [comment]
@KoltonMain7 This is a small nitpick, but it is convention to name your CSS file "styles.css". 🙂

**Comment by KoltonMain7** [comment]
> @KoltonMain7 This is a small nitpick, but it is convention to name your CSS file "styles.css". 🙂

Gotcha

**Comment by heyshadowsmith** [comment]
😬 The [preview deployment](https://personal-website-git-first-branch-koltonmain7.vercel.app/) from your last commit no longer has red text.

First 🪲!

**Review by heyshadowsmith — APPROVED** [review]
This is awesome! Approved! ✅

**Pull request merged**
